### ISSUE TITLE
Diosaban et al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#1]
**Title:**

FENCING AI; NEUROEVOLUTION OF AUGMENTING TOPOLOGIES (NEAT) TOWARDS COMPETITION AND SURVIVAL OF THE FITTEST IN A FENCING SIMULATION

**Members:**

BRYAN ABESAMIS, TIMOTHY DIOSABAN, ALYSSA DANIELLE MAGALLANES, NEIL RYAN SUSTIGUER

**Comment by geniusqwerty12** [comment]
Good afternoon. I've checked the following components of your thesis:
1) Manual: please include the logo of our College on the Cover Page as stated on the User Guide Specifications for the User Manual.
2) Manuscript: no problems for me, text are in the right font family and sizes, figures are clear.
3) Exe file: file was running normally, didn't find any bugs.

Don't forget to update the user manual on your repository.
Thank you

**Comment by maxemoose890** [comment]
Hello Sir! User Manual is now updated with the logos.

Thank you.

**Comment by geniusqwerty12** [comment]
@maxemoose890 
Good afternoon, ara na sa user manual inside the doc folder. Passing this to sir Mark for approval. 
Note: update your user manual on the Google Drive link also.

**Comment by maxemoose890** [comment]
Okay Sir updating it on the google drive too!
