### ISSUE TITLE
Recabar et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#10]
Title:

Implementation Of Haversine, Dijkstra’S Algorithm, And  Sarimax For Philippine Transport And  Fare Collection System

Members:

Recabar,  Bea Merr; Salcedo, Audrey; Santisteban, Tina Marie; Darle, Clarice Jane

**Comment by cictapps** [comment]
Initial comment: Not following thesis package guidelines https://github.com/wvsu-cict-code/thesis-package/wiki/Getting-Started#your-thesis-package

**Comment by mjsolidarios** [comment]
App tested. Encountered an issue with the map since it's difficult to navigate. Other components are working as well.
![Screenshot_20220408-070315](https://user-images.githubusercontent.com/7346165/162334124-b7303a54-6286-486e-aae1-3c611dca7030.jpg)

**Comment by mjsolidarios** [comment]
User manual is not following the recommended format. Please revise before we can release an approval.

**Comment by BeaMerr05** [comment]
Hello sir regarding the shortest path simulator you need to input the points first.
For example: 
From: 'A' after typing A you need to click Enter button 
To: 'C' then click Enter 

After that you'll see the output on the bottom. 

As for the user manual sir we will edit it right away. 

Thank you.

**Comment by dreysalcedo** [comment]
Hello sir additional lg regarding nga nag move ang mga components sa shortest path i believe na sa screen size. We used Pixel 4 when developing this. Regarding this shortest path design sir it is meant for visualization lg abi because wala kami may makita library nga maka visualize gd sng shortest path nga interactive like sa google maps.

**Comment by mjsolidarios** [comment]
I See..thanks for the clarification. Can you email me a video that you used for the demo in your last presentation? Thanks! mjsolidarios@wvsu.edu.ph

**Comment by dreysalcedo** [comment]
I have sent the video demo to your email sir. Please kindly check.

**Comment by mjsolidarios** [comment]
Software manual updated. Please add screenshots.
