### ISSUE TITLE
Vilchez et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#13]
**Title:**

Audio and Video Based Detection Of Stress Using Facial and Audio Cues Through Machine Learning

**Members:**

Audio and Video Based Detection Of Stress Using Facial and Audio Cues Through Machine Learning

**Comment by mjsolidarios** [comment]
Missing docs for thesis manual.

**Comment by mjsolidarios** [comment]
Thesis manual should follow the guidelines indicated. 
![image](https://user-images.githubusercontent.com/7346165/166224223-3bc62da8-adee-4871-97f5-5e5e13d6365e.png)

**Comment by cictapps** [comment]
Booklet to followup.
