### ISSUE TITLE
Amio et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#14]
**Title:**

Internet-of-Things Inventory Management System for Ultra-low Biofreezer in MQTT Framework

**Members:**

Amio, Castro, Sevilla, Soncio, Wong

**Comment by mjsolidarios** [comment]
* Missing thesis manuscript and raw files for the manual. 
* Missing default app credentials for login access.

**Comment by mjsolidarios** [comment]
Hardware presented and surrendered in school.

![279912757_1068484597355774_992962256020824437_n](https://user-images.githubusercontent.com/7346165/167960838-c05f87e5-e885-4fc1-a302-f94b41403d36.jpg)

**Comment by ayrrajane** [comment]
Update:
Uploaded thesis manuscript copy (pdf) and raw files (doc) for user manual
Uploaded READ.me/instructions for default app credentials inside the mobile_app folder

**Comment by ayrrajane** [comment]
Update:
Uploaded thesis manuscript raw copy (doc)
