### ISSUE TITLE
Tabaque et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#17]
**Title:**

Riceeta: On-Device Interference For Rice Leaf Disease Diagnosis And Treatment

**Members:**

Danica Marie A. Lebrilla, Lennox G. Luis, Prince Deo S. Solanib, Aris Ernst Tabaque

**Comment by mjsolidarios** [comment]
@arisernsttabaque Please remove "jeje" file on `dist`.

**Comment by arisernsttabaque** [comment]
okay na sir, na remove ko na

**Comment by mjsolidarios** [comment]
Thanks! Will process this later.
