### ISSUE TITLE
Taleon et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#21]
**Title:**
ScolioVis: Automated Cobb Angle Measurement on Anterior-Posterior Spine X-Rays using Multi-Instance Keypoint Detection with Keypoint RCNN

**Members:**
Carlo Antonio T. Taleon, Glecy S. Elizalde, Christopher Joseph T. Rubinos

**Comment by geniusqwerty12** [comment]
done checking the user manual and repository. The following changes are needed:
1. In the repository, in the src folder, there should be folders corresponding to the frontend/backend.

**Comment by Blankeos** [comment]
Thank you for the suggestions, sir. I have implemented the revisions in the most recent commit:
https://github.com/Blankeos/scoliovis/commit/1544cc259e79089bd165dae19afca4968cfd4e9e.

### 📑 Summary of changes made:
+ `frontend`/`backend` folders & readme docs in `/src`: [scoliovis/main/src](https://github.com/Blankeos/scoliovis/tree/main/src)
+ Updated the user manual to reflect the changes regarding installation of the package. (See [ScolioVis_UserManual.pdf](https://github.com/Blankeos/scoliovis/blob/main/doc/ScolioVis_UserManual.pdf), Page 3: Installation)

**Comment by geniusqwerty12** [comment]
Good morning @Blankeos, done checking the changes in the repo and user manual, all is working well. One minor thing on the user manual, page 13. The "Contact Us" page is not on page 15.
![image](https://user-images.githubusercontent.com/81214610/231030861-a5304280-2050-415a-bbb9-a3af0daac664.png)

**Comment by Blankeos** [comment]
Thank you for checking Sir @geniusqwerty12! Done with the minor revision in this latest commit: https://github.com/Blankeos/scoliovis/commit/469c8e83ee686948a2f0667dd8f1a0fb8e5a333d

### 📑 Summary of changes made:
- I updated [scoliovis/doc/ScolioVis_UserManual.pdf](https://github.com/Blankeos/scoliovis/blob/main/doc/ScolioVis_UserManual.pdf)

**Comment by geniusqwerty12** [comment]
Done checking the change on the user manual @Blankeos. We will wait for your manuscript to be finalized before closing this github issue. @cictapps

**Comment by cictapps** [comment]
Changing status for **certification**. @Blankeos please update the repo if the manuscript is already finalized. We can process your certification in advance.

**Comment by Blankeos** [comment]
Thank you Sirs @cictapps and @geniusqwerty12 for evaluating and certifying our thesis package. God bless! ✨
