### ISSUE TITLE
Caldina et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#22]
**Title:**
Insect Pest Identification  with Prescribe Pesticide on Rice Fields Using SSD Mobilenet Model on Deep Learning

**Members:**
Khrysma Dei Caldina, Clarence Gealon, Alyza Marie Tarrazona, Clarnick Yap and Paola Bianca Zarriz

**Comment by mjsolidarios** [comment]
Please follow package template format: https://github.com/wvsu-cict-code/thesis-package/wiki/Getting-Started#your-thesis-package

**Comment by mjsolidarios** [comment]
![image](https://github.com/wvsu-cict-code/thesis-package/assets/7346165/3a69aaea-fad8-4942-821c-3bfd6f85e3e8)
Missing thesis manual and manuscript @Leiszah  on the docs directory. Please also include the editable document files.

**Comment by cictapps** [comment]
Good day @Leiszah please put the following directories/files into a specific folder:
diectories:  .idea, app, gradle -> src folder
files: build.gradle, gradle.properties, gradlew, gradlew.bat, setings.gradle -> src folder

Please include a disclaimer.md containing the disclaimer for your thesis.

Follow up on your user manual inside the doc folder.

**Comment by Leiszah** [comment]
Good morning sir please check the revised contents through this link https://github.com/khrysmadei/Inspestor_App  
Thank you

**Comment by cictapps** [comment]
Good day @Leiszah, after checking the user manual and repository, here is my feedback:
1. change the folder name mobile to src
2. On the user manual, the system requirements section only contains the title but no content.
3. Please include the system requirements used for development, as well as the minimum system requirement for the mobile device where the app was installed.
4. Please include the software under the system requirements along with its version (the version that you used during development)

**Comment by Leiszah** [comment]
Good morning sir, we already made some changes sir please view the revised files through this link https://github.com/khrysmadei/Inspestor_App . Thank you sir!

**Comment by geniusqwerty12** [comment]
Good day @Leiszah, feedback 1, 2 and 3 are addressed in the thesis package. As for number 4, please include the SDKs, IDEs used during development (Android Studio, Kotlin) along with the versions under.

In the Getting Started/Usage section, add subsections based on the features (i.e. Loading/Starting Screen, Home Screen, Library Screen, Instructions Screen)
![image](https://github.com/wvsu-cict-code/thesis-package/assets/81214610/6269f9c5-64be-4264-9239-ad37a824310c)

Additionally, include the steps for the user to run the source codes (mobile app), starting from cloning the github repository, opening android studio and running the application

**Comment by Leiszah** [comment]
Good morning sir, we already revised this part please see the changes through this link https://github.com/khrysmadei/Inspestor_App

**Comment by cictapps** [comment]
Good day @Leiszah! The changes are present on the github repository! @mjsolidarios setting the status of the issue to for certification to start the process of the thesis package certification. Thank you!
