### ISSUE TITLE
Camarista et. al Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#24]
**Title:**
Deep Learning Based Dog Monitoring System Using Yolov4 And Computer Vision

**Members:**
Julliane Pearl Camarista, Xian Kyle Bejar, Elaisha Diana And Dave Zeus Nadura

**Comment by geniusqwerty12** [comment]
Feedback on the User Manual
1. Double check on the spacing, see pages 3 onwards, and the last page
2. Double check for grammatical errors, (you can use Grammarly)
3. Missing sections on the user manual:
a. Disclaimer
b. FAQs
c. Troubleshooting
d. Back cover

**Comment by camaristajp** [comment]
Noted sir. We have already implemented the changes in our User Manual sir kindly double check, Thank you!

**Comment by camaristajp** [comment]
For the changes, we added the disclaimer page, FAQs, Troubleshooting and Back Cover in the user manual. Also, we fixed the spacing and grammar.

**Comment by geniusqwerty12** [comment]
@camaristajp  Just checked the updated user manual, all of the missing contents, spacing, and grammar issues are fixed. Please upload the raw file (docx, pub) on the doc folder. @cictapps I'll proceed on checking the source code.

**Comment by geniusqwerty12** [comment]
@camaristajp please include in your user manual (system requirements) the versions of CUDA and cudnn, which is required by darknet, thank you

**Comment by geniusqwerty12** [comment]
Good day @camaristajp, all of the changes are present in the documentation. Also, include a pdf version of the user manual in the doc folder. Please upload the final version of the manuscript later in the doc folder.
@cictapps I'll change the status of this issue to for certification to process their thesis package certificate early.
