### ISSUE TITLE
Hibionada et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#25]
**Title:**
Gihápon: An Interactive Multi-Ending Visual Novel Adventure Game

**Members:**
Eisaac Hibionada, Andrea Villamor, Ma. Jessreigna Collado, John Cristian Suarez, Chemar Kristine Benitez

**Comment by anvllmr** [comment]
I have included the User Manual in the designated doc folder.

**Comment by anvllmr** [comment]
Good day, @mjsolidarios! I updated the user manual, added the manuscript, and I also included the required raw files.

**Comment by mjsolidarios** [comment]
Changing status for **certification**. Please update your documents in this repo after it was checked by the grammarian @anvllmr

**Comment by anvllmr** [comment]
Noted, Sir! Thank you.
