### ISSUE TITLE
Macorol et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#26]
**Title:**
Lagaw Ta

**Members**
Macorol, Pierre Angelo, Ocon, Max Ellison , Planco,Jam Roanne, Uy,John Rey, Young, Ma. Chelsea Joy

**Comment by cictapps** [comment]
Good day! 
Here are the feedback after checking your Github repository:
Mobile app: No problems installing, tested the application on a Samsung A30s
User manual:
1. Spelling errors: please fix the spellings error present in your user manual, here are the few that I found:
![image](https://github.com/wvsu-cict-code/thesis-package/assets/97827541/c47dc88f-6aa5-403d-8f03-096a905e03c8)
Change to React Native
![image](https://github.com/wvsu-cict-code/thesis-package/assets/97827541/55911122-e17a-48d4-828b-d280221f4258)
Change to Navigation
![image](https://github.com/wvsu-cict-code/thesis-package/assets/97827541/033cbcc8-279f-45e6-8bff-a9388992e186)
Change to Updating
Tip: you can use the Grammarly plugin on Word (if you used it) to check and spot for spelling and grammatical errors.

2. Installation requirements:
Remove Python from the requirements since it is not used for the mobile app development.
As for React Native, it needs additional software (Android Studio and SDK, NPM. You can follow the minimum requirements here for running React Native apps: apps here: https://learn.microsoft.com/en-us/windows/dev-environment/javascript/react-native-for-android

Also include the minimum requirements to run your mobile application

3. Running the mobile app
![image](https://github.com/wvsu-cict-code/thesis-package/assets/97827541/0721f063-1834-45e2-b008-01d9c8e09c48)
Revise the commands for running the mobile app.
you don't have a production/development server.
For installing dependencies, the command is: yarn install
Running the mobile app: yarn android OR react-native run-android
Createing apk/appbundle: yarn build:android / yarn bundle:android

4. If you have a keystore file generated, please put that inside the keys folder so that we can create and deploy the app.

**Comment by Uyjohn** [comment]
Keystore file uploaded already. To follow user manual edits

**Comment by Uyjohn** [comment]
Updated the User Manual Guide with revisions. Please check. Thank you!

**Comment by cictapps** [comment]
Good day @Uyjohn, all of the changes are present on the Github repo. @mjsolidarios changing the status for certification so that we can process the certificate in advance. Please upload the soft copy of your manuscript once it has passed the final checking, thank you!

**Comment by cictapps** [comment]
We have sent the completion certificate. Congratulations!
