### ISSUE TITLE
Abastillas et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#28]
**Title:**
Easi: A Text Simplification Mobile App using Natural Language Processing

**Members:**
Anghela Abastillas, Nathalie Elgaran, Cressida Jane Espino, Zenrick Parcon, and Abigail Kaye Unating

**Comment by keiruu** [comment]
Good day sir! would just like to clarify that we are from BSIT not from BSCS, thank you.

**Comment by cictapps** [comment]
Good day! After checking the thesis package, here are my feedback:
Mobile app: no issues were encountered while installing the application. Tried it on Samsung A30s.

User manual:
1. Please include a Title page (similar to the manuscript title page)
2. Update the system requirements
	For Flutter: include software requirements (Flutter SDK, Android Studio, Android SDK) for running the Flutter code
	For Python: include the Python version used
3. Installation
Please include the GitHub link before running the source code (both frontend and backend)
Please include the steps to run the Flutter code: 
		a. navigate to the frontend folder
		b. flutter pub get (installing dependencies)
		c. flutter run (running the application)
		d. include the steps on creating the APK

4. Usage
	Add sections on the Usage part. Separate each section (sections can refer to the features/screens present in your mobile app), and make sure to describe them accurately.
	a.Login:
	b. Sign up:
	c. Home page:
	    c.1. Typing:
	    c.2 Picture:
	d. History
	e. Profie
Please include the screenshots for other features

**Comment by keiruu** [comment]
Good evening sir @cictapps. I applied the changes you mentioned in this [commit](https://github.com/keiruu/easi/commit/ecc29531315aa839fc868b727ac33dc0c406feb3). Thank you!

**Comment by cictapps** [comment]
Good day @keiruu, all of the changes are present in the user manual.
Also tested the backend, all is running well with minor changes.
For the manual, please do the following
1. On running the backend, the env creation and activation should be before the module installation (pip install..) so that the modules are installed on the created environment, not on the system.
![image](https://github.com/wvsu-cict-code/thesis-package/assets/97827541/666ef5de-97a0-49ae-92ff-993d6a5409cf)

2. Add borders to the app screenshots like you did on the Login/Sign up. 
![image](https://github.com/wvsu-cict-code/thesis-package/assets/97827541/c8f0973c-26ca-4f8d-b79c-5f7aeec814fa)

**Comment by keiruu** [comment]
Good afternoon sir, I modified the manual in this [commit](https://github.com/keiruu/easi/commit/aa47796f5c7426c82ab3e6762f2a59031ab18cc7). Thank you!

**Comment by cictapps** [comment]
Good day @keiruu, the changes are present on the manuscript. Remember to upload the final version of your thesis in the github repository later.

@mjsolidarios changing the status to for certification so the certificate can be processed in advance.

**Comment by cictapps** [comment]
We have sent the completion certificate. Congratulations!
