### ISSUE TITLE
Galvez et al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#3]
Title:

Integration of QR Code Technology to WVSU Feedback System with Data Encryption using RSA Algorithm

Members:

Mike Jan Galvez, Veronica Rose Garcia, Andrei Emmanuel Gentica, Kristian Allan Cabida

**Comment by mjsolidarios** [comment]
Missing thesis docs and manual. Please upload the additional requirements.

**Comment by mjcgalvez** [comment]
Hello sir, good day. We already uploaded our thesis manuscript and thesis manual. Thank you.

**Comment by mjsolidarios** [comment]
System tested with minor recommendations:

![image](https://user-images.githubusercontent.com/7346165/154593583-db82c366-56a9-4396-8f33-542d40d2b4ea.png)
![image](https://user-images.githubusercontent.com/7346165/154593759-cc050483-79de-44c2-b3a8-3cdf8eb31711.png)

Recommendations: 
* Please replace all absolute web URLs to relative ones for the system to work properly on a different server. This can be done easily in VSCode
![image](https://user-images.githubusercontent.com/7346165/154594540-e9b31bbf-c34e-4088-9910-4253d905f18c.png)
