### ISSUE TITLE
Bentain et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#30]
**Title**
Utilization of Shaders Algorithm to Simulate a 3D Isometric Game

**Members**
Eduardo Bentain III, John Carlo Combalicer, John Benedict Santerva, Kenette Roeven Saylo

**Comment by geniusqwerty12** [comment]
The executable file is running without errors.
As for the documentation, here are my feedbacks:
1. Include system setup (hardware and software) for development, include the IDEs, version of unity
2. In the installation, add another section on how to setup the environment and run the project
3. On the first part of the installation, also include the github link where the exe exists. Include it also on the dev setup.

**Comment by Ashvalano** [comment]
hello sir @geniusqwerty12 , we have implemented the changes needed on our user manual.

**Comment by geniusqwerty12** [comment]
Good day @Ashvalano, all of the changes are present in the user manual. @cictapps moving the status to for certification to prepare the processing in advance.

**Comment by cictapps** [comment]
We have sent the completion certificate. Congratulations!
