### ISSUE TITLE
Batugon et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#32]
**Title:**
Traze: A Real-Time Routing, Scheduling, and Monitoring Android Application for Delivery Services using Dijkstra Algorithm and Ant Colony Optimization

**Members:**
Krisna Jean Batugon, Jean Formento, Maria Arlyn Fuerte, Jewel Josef Jasper Morales

**Comment by Mariaarlyn14** [comment]
@geniusqwerty12 Good day, Sir. We have already updated our [user manual](https://github.com/Mariaarlyn14/Traze/blob/main/docs/User-Manual-Traze.pdf). If you have difficulty opening the file please let me know. Thank you

**Comment by cictapps** [comment]
Good day @Mariaarlyn14, feedback, 1, 2, 4, and 5 are on the user manual.
Please include the version of Python used in the System Requirements section.
As for number 3, please do the following:
1. Please include the Python environment creation and activation.
2. Also include the steps for running the mobile application source codes.
3. As for the steps for running the algorithm, you can reduce the number of screenshots to reduce the total number of pages.

**Comment by Mariaarlyn14** [comment]
Good Day Sir, @geniusqwerty12. We have already updated the [user-manual](https://github.com/Mariaarlyn14/Traze/blob/main/docs/User-Manual-Traze.pdf) and also made various changes in the repository. If you have any questions or have difficulty opening the files, please let me know. Thank you

**Comment by cictapps** [comment]
Good day @Mariaarlyn14, all of the changes are present in the user manual. @mjsolidarios moving this issue to for certification to process their thesis package certificate in advance.

**Comment by Mariaarlyn14** [comment]
Will do Sir, Thank you.

**Comment by cictapps** [comment]
We have sent the completion certificate. Congratulations!
