### ISSUE TITLE
Denosta et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#35]
Title:
EFFECTIVE HOSPITAL RECOMMENDATION OF CRITICAL CASES USING A PRECISION EMERGENCY RESPONSE APPLICATION BASED ON A MULTI-LABEL K-NEAREST NEIGHBORS (ML-KNN) ALGORITHM

Members: 
Denosta, Jed Adrian R.; Pacificar, Natalie Jane S.; Malimit, Luie John G.; Atinon, Mark Vincent A.

Github link/s:
Backend: https://github.com/thesis-buddies/laravel-backend
Frontend: https://github.com/thesis-buddies/thesis-iloilo-city-hospital-recommendation-system
Microservice(Flask): https://github.com/thesis-buddies/flask-microservice

**Comment by cictapps** [comment]
Please consolidate all the source codes (frontend, backend, microservice) into one repository, the same with the documents (manuscript and user manual) should be in the doc folder.

![image](https://github.com/wvsu-cict-code/thesis-package/assets/97827541/3b1f56bf-a7d6-4efc-82f6-e3083d792a86)

**Comment by cictapps** [comment]
Checked the installation part of the application (frontend, microservice, and backend), and here is my feedback:
1. Before installing the Python modules, please include a Python environment creation and activation.
![image](https://github.com/wvsu-cict-code/thesis-package/assets/97827541/18855145-d66b-403f-893b-b6ef60fca44c)

2. Please include the versions of the software used (Python, Node.js, Composer and XAMPP). You can list the software needed after the Hardware requirements section.

I will check the usage section next.

**Comment by Luieka224** [comment]
Noted sir @cictapps !

**Comment by Luieka224** [comment]
Hi Sir @cictapps ! We have updated our codebase and release to reflect the necessary changes.

**Comment by geniusqwerty12** [comment]
Good day @Luieka224, all of the changes are present in the user manual. Please follow up the final version of your manuscript later. @mjsolidarios changing the status of this issue to for certification to process their thesis package certificate in advance.

**Comment by JedAdrianDenosta** [comment]
Thank you very much, Sir @cictapps and @geniusqwerty12  🫶✨

**Comment by cictapps** [comment]
We have sent the completion certificate. Congratulations!
