### ISSUE TITLE
Denura et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#37]
Title:
Hues of You: A 2D Interactive Animated Short Film

Members:
Hilary Ann P. Denura, Ma. Dyzza E. Espino, Lara Dionise Marie F. Loretizo, Nissi Joy A. Mana-ay, Winzee Dawn C. Panunciar

Animation Link: https://drive.google.com/drive/folders/1Zbf3hKiGeuiep9HaEi7aQLXynRAJa8jp

Remarks: 
We use Google drive to store the .exe application, since Github cannot store over 1GB data file. 
Download the File from the Google Drive Link provided above, Select the dll, Open “HuesOfYou-A-2D-Interactive-Animated-Short-Film-Application” file, Inside the “HuesOfYou-A-2D-Interactive-Animated-Short-Film-Application” file, open the “Build_App” file, Open the “huesofyou.exe” file and wait for it to open.

**Comment by mjsolidarios** [comment]
Package checked. Please upload the editable files for your thesis manual and manuscript.
