### ISSUE TITLE
Alaestante et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#39]
**Title:**
Personal Fitness Program Recommendation Application Using Image Processing With Progress Monitoring Using Video Analysis

**Members:**
Jan Michael R. Alaestante, Esther Joy P. Dadivas, Michael L. Equilla, Fritz Yev T. Gelito, Jay Anne P. Soqueño

**Github URL**
https://github.com/EjDadivas/FinalWorkoutVideoAnalysis.git

**Comment by BSIT4BNISMike** [comment]
Good evening sir na edit na namon based sa recommendations sir

**Comment by cictapps** [comment]
Good day @BSIT4BNISMike, all of the changes are present in the Github repository. Please follow up the final copy of the manuscript (both docx and pdf file) later. 
@mjsolidarios moving the status of this issue to for certification to start the processing of their thesis package certification.

**Comment by BSIT4BNISMike** [comment]
thanks sir. I uploaded the final manuscript, both PDF and docx file.
