### ISSUE TITLE
Duero et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#40]
**Title:**
Recede: A Social Distancing System Using Esp32 Microcontroller And Bluetooth Low Energy For Peer-To-Peer Warning Signal

**Members:**
Duero, Catherine G., Esperela, Jason P., Godin, John Ray T.,Jover, Jellie Marie J., Parreño, Albert S.

**Comment by geniusqwerty12** [comment]
Good day! After checking the GitHub repo, here are my feedback:
1. Please follow the structure for the standalone app stated in the instructions, put the folders (arduino, dashboard and database) inside the src folder. As for the other folders (lib, config, dist) you can ignore them.
2. For running the dashboard in the User Manual, specify the PHP version used, preferred IDE to use, command to run the server, how the user can access/see the server.

**Comment by johnraygodin** [comment]
Good Day, sir!

Your feedback has been noted. We'll work on the revisions as soon as possible.
Thank you.

**Comment by johnraygodin** [comment]
Good day, sir!

We already have revised our thesis package according to your recommendations.
Please have it checked on you convenient time.
Thank you very much.

https://github.com/johnraygodin/recede/tree/main

**Comment by mjsolidarios** [comment]
Thanks @johnraygodin! Tagging Sir @geniusqwerty12

**Comment by geniusqwerty12** [comment]
After checking the updates, number 1 is done. As for number 2, I saw that the versions of the software was included on a file inside the folders, but not on the User Manual. Please include the versions inside the user manual.

**Comment by johnraygodin** [comment]
Good day, sir.

Thank you for the assessment. We'll work on it.

**Comment by geniusqwerty12** [comment]
@johnraygodin follow up on the status of the thesis package.

**Comment by johnraygodin** [comment]
Good Day, sir.

We now have uploaded the revised version of our user manual, applied the needed changes, along with the revisions that ma'am Janine has suggested.

Thank you

**Comment by mjsolidarios** [comment]
Thank you @johnraygodin! Following up on this Sir @geniusqwerty12. Thank you!

**Comment by geniusqwerty12** [comment]
Good day @johnraygodin! The changes are found on the user manual. One final issue, please include a Contact Us page with the list of names and contact info of the researchers and the back cover for your manual. Thank you!

**Comment by johnraygodin** [comment]
Good Day, sir.

Noted. We'll work on right away.
Thank you

**Comment by johnraygodin** [comment]
Good day, sir. 

We now have applied the needed changes and reuploaded the user manual. 
Please have it checked on your convenient time. 
Thank you!

**Comment by geniusqwerty12** [comment]
@johnraygodin the Contact Us page and back cover are present in the user manual. Don't forget to upload the final version of your manuscript later.

@mjsolidarios @cictapps setting the status to for certification to process their certification for thesis package.
