### ISSUE TITLE
Garcia et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#41]
**Title:**
Focust, A Focus Training App Using Eye Tracking

**Members:**
Elmar Cris Garcia, Asther Louie Cabardo, Wil Ann Grace Teves, John Cedric Sideño, Joshua Andrei Ventura

**Comment by cictapps** [comment]
After downloading and checking the thesis package, here are the feedback:
1. Follow the folder structure for the web app: https://github.com/wvsu-cict-code/thesis-package/tree/master/web_app_games/web_app_or_game_name. The files and folders related to the source code should be stored inside a folder called "src"
2. For running the source code, specifically on installing the modules on Windows, there are some modules that are not present /available for Windows (i.e mediapipe-silicon and all of the pyobjc). Once it removed it from the requirements.txt, I was able to run the web. For this, you should create two requirements.txt, one for windows and macOS (requirements-win.txt & requirements-macos.txt). Don't forget to specify these on the User Manual (Getting Started, 2.4)
3. On the User Manual, in Getting Started, section 2.3, on number 2, include command to be run on Windows
4. Page 9 is a duplicate of the Loggin In steps.

**Comment by ashcbrd** [comment]
I have carefully reviewed and incorporated your feedback, making the necessary revisions and fixes to enhance the project's quality. These are the key improvements:

1. Folder Structure: I have adhered to the correct folder structure, ensuring that the project is organized and easily navigable.

2. requirements.txt for MacOS and Windows: To cater to both MacOS and Windows users, I have created two separate requirements.txt files, each tailored to the specific operating system. 

3. User Manual Enhancements: In section 2.3, specifically within step 2 of the user manual, I have included the command to be executed on Windows systems. 

4. Improved User-Friendly Instructions: I have resolved the user manual issue by fixing the steps and eliminating any duplicated pages.

**Comment by cictapps** [comment]
Good day @ashcbrd! The PDF file for the user manual is corrupted. Also, please put the folders .idea and public within the src folder as well as the requirements.txt.

**Comment by ashcbrd** [comment]
Thank you sincerely for reviewing the thesis package. Your expertise and attention to detail have been invaluable in ensuring its quality.
 
I apologize for any inconvenience caused. I have identified a mistake in the email addresses provided in the Google Forms for two of my team members. I would like to request sir @mjsolidarios to kindly assist with the following corrections:
 
1. John Cedric Sineño:
   Correct Email: johncedric.sideno@wvsu.edu.ph
 
2. Will Ann Grace Teves:
   Correct Email: willann.teves@wvsu.edu.ph
 
Your understanding and prompt attention to this matter are greatly appreciated. Once again, we are truly grateful for your invaluable contribution in reviewing the thesis package.
