### ISSUE TITLE
Arlanza et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#43]
**Title:**
A Human Counting For Crowd Control And Social Distancing System Using Image Recognition

**Members:**
Sheina A. Arlanza, Jhemer Cris B. Colas, Albert Anthony F. Polong, J-Anne S. Soliva, Charles D. Villafuerte

**Comment by geniusqwerty12** [comment]
After checking the User Manual, here are some minor feedback that needs to be addressed.

1. In the Software Installation section, please include the commands used to run the application
2. (Optional) on the same section, use numbers (1,2,3...) to indicate the steps instead of alphabetical.

**Comment by Jhemercolas** [comment]
> 

Hello Sir, we've updated our User manual.

**Comment by geniusqwerty12** [comment]
Good day @Jhemercolas! All of the feedback is on the current version of the user manual. @cictapps setting the status of this issue to for certification to start on processing their thesis package certification.

Also @Jhemercolas don't forget to upload the softcopy of the final version of the manuscript (if the current pdf is not yet final) in the github repository.

**Comment by Jhemercolas** [comment]
Thank you sir for the time and patience in checking our thesis package.
