### ISSUE TITLE
Gemalaya et. al. Package Certification

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#47]
**Title:**
Thesis Progress Monitoring And Archive Management System  For West Visayas State University College of Information and Communications Technology

**Members:**
Dion Rey Gemalaya, Evelyn Sotela, Eden Faith Tagudando, Angie Rose Azucena

**Comment by cictapps** [comment]
Awaiting email reply from any team members.

**Comment by Lamronba** [comment]
Hello, sir, and good morning. We apologize for the delay. The team decided to submit a response on Thesis Tracer 2023 and made a new repository due to a submodule error. Here is the new link for our thesis. Thank you for your understanding. https://github.com/dreygmly13/TPAM_WEST/

**Comment by mjsolidarios** [comment]
Just finished reviewing @Lamronba . Your package is missing your editable files for your **User Manual** and **Thesis Manuscript**. Thank you as well for the followup!

**Comment by Lamronba** [comment]
Good morning, sir. The team updated the package with the missing editable files, the user manual, and the manuscript. Thank you.

**Comment by mjsolidarios** [comment]
Thanks @Lamronba ! Done reviewing your package. Forwarding this for certification.

**Comment by Lamronba** [comment]
Thank you sir.🖤
