### ISSUE TITLE
Amarillo et. al. Package Certification

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#48]
**Title**
Mobile Application Monitoring System for Proper Care of High-Value Ornamental Plants with QR Code Integration

**Members**
Amarillo, Angelo Joseph; Bacugan, Reniel Graye; Lomenario, Julius; Navigar, Amiel; Sumido, Arlai Zann

**Comment by cictapps** [comment]
Good day!!
Upon checking the GitHub repository, please upload the final version of your manuscript and put it inside the docs folder along with your user manual.

**Comment by lowkeycrystal** [comment]
Greetings!
The final version of our manuscript has been added to the repository, inside the doc folder. Thank you!

**Comment by cictapps** [comment]
Done checking the attached manuscript @lowkeycrystal . One last thing is that the user manual requires a back cover, please provide one.

**Comment by lowkeycrystal** [comment]
I fixed it, sir.  I appreciate your patience.

**Comment by cictapps** [comment]
The package is complete, thank you @lowkeycrystal. @mjsolidarios pushing this to certification label.
