### ISSUE TITLE
Acanto et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#49]
**Title:**
Rabbit Raising Monitoring System With Recommendation For Meat Production Application

**Members:**
Jeremiah F. Acanto
Rosemarie E. Edang
Rubie Joy C. Cahong
Jeed Galiwan
John Michael Tan

**Comment by geniusqwerty12** [comment]
Here are the comments and suggestions I've found on the submitted Github repository:

1. Github structure
	a. put inside lib folder add requirements.txt

	b. please put the source codes, and folders created by the python environment (Lib, Scripts) inside a folder called "src" (see comment below for the files related to the python environment)

	c. put the pyvenv.cfg inside a folder called "config"

2. User manual
	a. some of the figures don't have an explanation, please provide explanations to said figures.

	b. the make sure that the instructions for setting up the python environment matches the actual structure of the source code given. It is better for you to delete all of the files and folders created by the py environment.

	c. Please place the terminal commands found in the figures into text, so that other users can easily enter the commands.

**Comment by geniusqwerty12** [comment]
Good day! After checking the thesis package, please see the comments that you need to address:
1. github repo
		what are the folders "share" and "etc"? if these are configurations, please put them inside the "config" folder, if these are libraries, put them inside a "lib" folder, otherwise just put them inside the src folder

Aside from these, address the previous comments that you didn't comply.
		1a, 1c and 2a

once done, please merge correction_v1.1 and other corrections to the main branch.

**Comment by miah0917** [comment]
Good day sir. Already done transferring folders share and etc. also added requirements.txt to lib folder and transferred pyvenv.cfg to config folder. Lastly, already done updating the user manual and merged all the necessary file to the main branch

**Comment by geniusqwerty12** [comment]
Good day! @miah0917 after checking the github repository, all of the remaining concerns were addressed. 
Passing this to @mjsolidarios for certification.
