### ISSUE TITLE
Tangub et al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#5]
Title:

Implementing First-In First-Out(Fifo) Queue Algorithm For Task Scheduling Of Wisp: An Assistive Application

Members:

Fritz Bryan N. Angulo Amiel John B. Macahilo Kristara C. Mendoza Vijay Tangub

**Comment by mjsolidarios** [comment]
@SoneVijay Package is not following the proper format for android apps. Please check the guide again. Thanks!

**Comment by SoneVijay** [comment]
Good evening sir @mjsolidarios  , I have already updated our repository. Thank you sir! ☺
