### ISSUE TITLE
Bellido et. at. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#50]
**Title:**
SafetyPin: A Web Application for Crime Pattern Analysis through Heatmap Visualization and Safe Route Recommendation  for Enhancing Citizen Safety

**Members:**
Jeno D. Bellido, Rey Anne Destua, Ariane Marie Lavilla, and John Cairo Minerva

**Comment by geniusqwerty12** [comment]
Please upload the following documents (in pdf) and put it inside a folder called "docs"
1. User Manual
2. Final version of the thesis (ready for bookbinding)

**Comment by geniusqwerty12** [comment]
After checking both the user manual and source code, please see the following comments:
	1. insert the URL for your web app on the instructions (or where to find the URL)
	2. reformat the title page, similar to the manuscript's title page

**Comment by jeno-bellido** [comment]
@geniusqwerty12 Good morning, Sir. I uploaded the documents na sir sa github. Thank you.

**Comment by geniusqwerty12** [comment]
Good day @jeno-bellido, you have complied with the comments presented after checking the updated github repo. @mjsolidarios passing this to for certification
