### ISSUE TITLE
Absalon et. al. Package Certification

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#51]
**Title:**
Healthy Broiler Chicken Verifier System

**Members:**
Arc Nil L. Absalon
Julian Anthony P. Aguirre
Exekiel M. Dela Cruz
Cember Mae B. Paborada
Hector G. Paniergo

**Comment by geniusqwerty12** [comment]
Good day! 
After checking the github repo you've submitted, please check the following comments:

1. did you make a keystore, which is needed to make an APK build for release? If so please include it with a txt file containing the passwords
2. there is something wrong with the apk, the file size should be in mb, not 1 KB only. I cannot install the apk file in my device.
3. upload the user manual later

**Comment by NilArc** [comment]
Recreated the repository due to storage limit. The repository link is still the same, and new invitations have been sent.

**Comment by geniusqwerty12** [comment]
Good day @NilArc , after checking the new thesis package link, all of the concerns were addressed.

New link:
https://github.com/NilArc/hbcv

@mjsolidarios passing this to your for certification
