### ISSUE TITLE
Parcon et. al. Package Certification

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#56]
**Title:**
Modeling and Prediction of Infectious Disease Cases in Iloilo City Using Multiple Linear Regression

**Members:**
Hiro Grande Parcon
Regina Flor Tonogbanua
April Joy Narciso Gallano
Joan Marie Arsenio
Arle Kai Gorriceta

**Comment by geniusqwerty12** [comment]
Good day! After checking your submitted github repository, here are my suggestions that you need to implement:
	Source code
		1. github structure - please follow the structure for the web_app
			src
			doc

		2. remove redundant files
			clf.pkl and covid.csv from the root directory, since they are already/should be in the src folder

		3. include the soft copy of the final version of your thesis in the doc folder

	User manual
		1. prepare a back cover
		2. similar to your thesis manuscript, put figure numbers and titles so that you can easily refer it in your steps/descriptions
		3. remember the user manual is a booklet type, make sure to adjust the size properly

**Comment by 11hiro** [comment]
Good Afternoon Sir Mateo @geniusqwerty12 we already complied the comments for the thesis package certification

**Comment by geniusqwerty12** [comment]
Good day @11hiro, I have some questions regarding the current state of your user manual
1. is page 23 the back cover of the manual? It seems blank sya with a page number below. If so, please put something, and remove the page number para maging back cover sya.  
The rest of the of the comments were addressed.

**Comment by arlekaidot** [comment]
Hi sir @geniusqwerty12, last page has been removed and replaced with a cover page instead. Thanks!

**Comment by geniusqwerty12** [comment]
@arlekaidot done checking the updated user manual
@mjsolidarios setting this issue to for completion
