### ISSUE TITLE
Solvero et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#6]
Title:

Graphics Axis Platform for Graphic Designers with Robust Image Watermarking Technique for Copyright Protection

Members:

Hermenia Bucana, Denise Marie Gegrimal, Juisa Grace Solvero & Nina Kae Sumaculub

**Comment by mjsolidarios** [comment]
* App module missing from code base.
```
Traceback (most recent call last):
  File "/home/solidarios/Repositories/graphics_axis/src/run.py", line 1, in <module>
    from graphics import app
ImportError: cannot import name 'app' from 'graphics' (unknown location)

Process finished with exit code 1
```

* In the user manual please use the CICT logo without the gray background.
* Create a requirements.txt file inside the src folder and included the needed python dependencies to run the system. Please [read](https://boscacci.medium.com/why-and-how-to-make-a-requirements-txt-f329c685181e) this article to learn more.

**Comment by issagrace** [comment]
Good day. The project folder has been updated sir, same with the user manual. We also included the library dependencies in the requirements.txt file in the src folder. Thank you..

**Comment by mjsolidarios** [comment]
Got this. Thanks! Will keep you updated after testing.

**Comment by mjsolidarios** [comment]
System is now tested and running, even if the static routes are already updated but it can't locate the images - probably because of the Linux setup. Nevertheless, this is now ready for certification. 
![image](https://user-images.githubusercontent.com/7346165/162359582-82be5dd4-fa24-4add-a42d-cce57a5980e3.png)
