### ISSUE TITLE
Espares et. al. Package Certification

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#63]
**Title:**
SignTalk: An Android-based Mobile Application for Sign Language Translation Using CNN Algorithm and TensorFlow Lite Tool

**Members:**
Espares, Gene Darwin; Narciso, Syra

**Comment by geniusqwerty12** [comment]
Good day! Here are some of the feedback I saw from the thesis repository that needs to be addressed:
USER MANUAL:

1. fix page 2, format similar to the title page in your thesis manuscript

2. add figure labels, similar to your thesis manuscript on figures

3. add numbering to the steps taken by the user (usage per feature)

4. add Troubleshooting section to your user manual

GitHub repo:
1. transfer the MANUAL file to the "doc" folder, and add your final version of the manuscript.

**Comment by genedarwinespares** [comment]
Good day, Sir! Commenting here to inform you that we have integrated all the comments to the revised Manual and moved it to "doc" folder. Thank you.

**Comment by geniusqwerty12** [comment]
Good day @genedarwinespares, all of the changes were made in the GitHub repository. Please upload the final version of the manuscript once Dr. Cabacas has done checking it.
Sir @mjsolidarios moving this issue to for certification.
