### ISSUE TITLE
Bañares et. al. Package Certification

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#64]
**Title:**
A Nutrient Deficiency Detection With Foliar Fertilizer Recommendation Application Using Hybrid Algorithm For Guimaras Carabao Mango Leaves

**Members:**
Erica Clarice A. Bañares
Airah Mae A. Cabangal
Glen Hedrick O. Canto
Norberto D. Deli Jr.
Angelica Grace P. Simbran

**Comment by geniusqwerty12** [comment]
Good day!
Please upload a soft copy of your user manual in the docs folder.

**Comment by Jngkay** [comment]
Good afternoon, sir. 

I have uploaded the softcopy of our application's user manual.

**Comment by geniusqwerty12** [comment]
Good afternoon ma'am @Jngkay, there are no more questions/comments/suggestions I found on your github repository.
sir @mjsolidarios moving this issue to certification.
