### ISSUE TITLE
Aguirre et. al. Package Certification

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#65]
**Title**
Islas de Gigantes: A myth Preservation Through Game Creation

**Members**
Jose Eduardo Aguirre, Kystal Ann Sayco, April Princess Suelo, Haron A. Uka Jr. , Camille B. Vapor

**Comment by mjsolidarios** [comment]
![image](https://github.com/user-attachments/assets/9df4e65e-9967-42fc-8edf-2f036aebc407)
The file structure does not follow the recommended organization. Please read the instructions again.

**Comment by prlprncs** [comment]
Here sir ang link for our gdrive https://drive.google.com/drive/folders/18sc_FCKjHgh8iFJ6-YLydmd0_BuInND_

**Comment by mjsolidarios** [comment]
New link: https://drive.google.com/drive/folders/18sc_FCKjHgh8iFJ6-YLydmd0_BuInND_
