### ISSUE TITLE
Millares et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#7]
Title:

AI/ML for Anomalous Surveillance: A Detection and Alert System

Members:

Francis Rey Soldevilla, Francine Anne Millares, Jesmar Troy Adolacion, & Nezel Leagogo

**Comment by geniusqwerty12** [comment]
Problem 1:
Followed the instructions given on the github repo, tried to run it using VSCode but encountered an error.

C:\Users\Tope-WVSU\Documents\GitHub\AIML_Detection_System\src> python Main.py
Traceback (most recent call last):
  File "C:\Users\Tope-WVSU\Documents\GitHub\AIML_Detection_System\src\Main.py", line 113, in <module>
    iconA = Image.open("./src/index/Wcamera.png")
  File "C:\Users\Tope-WVSU\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './src/index/Wcamera.png'

Setup

Windows 10

Python Version
C:\Users\Tope-WVSU>python --version
Python 3.9.7

**Comment by ILoveRedEd55** [comment]
Good morning sir!

I have pinpointed the problem. It seems that you need to open the folder first in VS Code then navigate to the 'Main.py' file and run the program.

Will be updating the README instructions to address the problem in case the user encounters it.

**Comment by geniusqwerty12** [comment]
I already navigated to the src folder before running the Main.py on the command prompt

**Comment by geniusqwerty12** [comment]
@ILoveRedEd55 please check this console logs.

PS C:\Users\Tope-WVSU\Documents\GitHub\AIML_Detection_System> cd src
PS C:\Users\Tope-WVSU\Documents\GitHub\AIML_Detection_System\src> python Main.py
Traceback (most recent call last):
  File "C:\Users\Tope-WVSU\Documents\GitHub\AIML_Detection_System\src\Main.py", line 113, in <module>
    iconA = Image.open("./src/index/Wcamera.png")
  File "C:\Users\Tope-WVSU\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './src/index/Wcamera.png'

When I updated the directory of the images below:
iconA = Image.open("./src/index/Wcamera.png")
iconAa = Image.open("./src/index/Wcamera.png")
iconAb = Image.open("./src/index/Wcamera.png")
iconAc = Image.open("./src/index/Wcamera.png")

to 

iconA = Image.open("index/Wcamera.png")
iconAa = Image.open("index/Wcamera.png")
iconAb = Image.open("index/Wcamera.png")
iconAc = Image.open("index/Wcamera.png")

Fixes the problem and the GUI showed, but when I tried to click the Drowsiness Detection, I encountered this error

PS C:\Users\Tope-WVSU\Documents\GitHub\AIML_Detection_System\src> python Main.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Tope-WVSU\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Tope-WVSU\Documents\GitHub\AIML_Detection_System\src\Main.py", line 41, in drowsiness
    term1 = Popen (["./lib/env/drowsiness_env/python", "./src/drowsiness-detection.py"])
  File "C:\Users\Tope-WVSU\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Tope-WVSU\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by geniusqwerty12** [comment]
![image](https://user-images.githubusercontent.com/81214610/160748363-82338603-2872-4548-80d1-b9bd839d52bc.png)

![image](https://user-images.githubusercontent.com/81214610/160748447-aad61b31-acdd-42b0-ade5-c87a7470099f.png)

**Comment by geniusqwerty12** [comment]
Tested the application via Debugging with Python version 3.6.1.
Performance was laggy (might be due to the Debugging).
So far tested the Drowsiness and Weapons Detection functionality, as for others (Violence and Falling Detection), I am not sure on how to proceed.

**Comment by geniusqwerty12** [comment]
After checking the updates made on the repository, here are my feedback:
1. add the requirements.txt file to the config folder.
2. For the User Manual, please add the steps on how to run the source code, including the system requirements and software required to run the codes.
3. For the User Manual, kindly follow the structure on this link: https://github.com/wvsu-cict-code/thesis-package/blob/master/MANUAL.md . You can put a hardware and a software section to distinguish the camera/lcd from the program.
4. Please follow the page layout: Letter-sized booklet type (bifold) (8.5"x11.0")

**Comment by geniusqwerty12** [comment]
User Manual is now okay, waiting for the manuscript.

**Comment by cictapps** [comment]
Followup on this @ILoveRedEd55 .
