### ISSUE TITLE
Cordero et. al. Package Evaluation

### ISSUE THREAD

**Issue by cictapps** [wvsu-cict-code/thesis-package#8]
Title:

Physician Shift Scheduling and Monitoring System using Constraint-Based Algorithm

Members:

Rica L.  Cordero, Shenly Jazreel Redondo, Elme Joy Basco, Ella Marie Moises

**Comment by mjsolidarios** [comment]
Issue with PHP code:
```

An uncaught Exception was encountered

Type: ParseError

Message: Unclosed '{' on line 638

Filename: application/models/Auth_model.php

Line Number: 712

Backtrace:

File: /application/controllers/Auth.php
Line: 14
Function: model

File: /home/solidarios/public_html/index.php
Line: 315
Function: require_once

```

**Comment by ricaCor** [comment]
Good morning sir, pleased use 7.2 version of XXAMP dayun sa php.ini pki on sang short open tag.


short_open_tag = On


Detailed instructions ara sa config/ Server and Application Configuration.

Thank you!

**Comment by ricaCor** [comment]
After ma on sir, paki restart nalng sang Apache. Thank you!

**Comment by mjsolidarios** [comment]
I see...sa Linux ko ni gin run abi. Already did the short_open_tag setting. Try ko sa Windows.

**Comment by ricaCor** [comment]
Thank you sir, please try. We encountered the same error before naman, na notice ko na ang error based sya sa version sang XXAMP nga gina gamit kg dapat sa database.php... ang password naka set sa ('password' => ' ' ,) .

**Comment by mjsolidarios** [comment]
Resolve errors but page redirects and prevents logging in to the system.
![image](https://user-images.githubusercontent.com/7346165/162349452-1c986048-c87e-466d-a12a-5f17a8105891.png)

**Comment by mjsolidarios** [comment]
System tested - use only the recommended XAMPP version.

**Comment by ricaCor** [comment]
Thank you sir!
